# List of Exposures with Flats


- work with Weakly_2022_09
- use jupyter kernel LSST



- author : Sylvie Dagoret-Campagne
- affiliation : IJCLab
- creation date : 2022/06/17

In [1]:
! eups list -s | grep LOCAL

atmospec              LOCAL:/sps/lsst/groups/auxtel/softs/shared/auxteldm_gen3/repos/w_2022_09/atmospec 	setup
eups                  LOCAL:/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2022_09/conda/envs/lsst-scipipe-2.0.0/eups 	setup
rapid_analysis        LOCAL:/sps/lsst/groups/auxtel/softs/shared/auxteldm_gen3/repos/w_2022_09/rapid_analysis 	setup

In [2]:
! echo $IMAGE_DESCRIPTION
! eups list -s lsst_distrib

   g64fc59b30a+e1dba0a6f6 	w_latest w_2022_09 current setup

In [3]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
from matplotlib.colors import LogNorm

from mpl_toolkits.axes_grid1 import make_axes_locatable

import matplotlib.ticker                         # here's where the formatter is
from matplotlib.ticker import (MultipleLocator, FormatStrFormatter,
                               AutoMinorLocator)

from astropy.io import fits

In [4]:
import lsst.afw.display as afwDisplay
afwDisplay.setDefaultBackend('matplotlib')

In [5]:
import lsst.daf.butler as dafButler

In [6]:
repo = '/sps/lsst/groups/auxtel/softs/shared/auxteldm_gen3/data/butler.yaml'
butler = dafButler.Butler(repo)
registry = butler.registry

## List of Exposures

In [7]:
df_exposure = pd.DataFrame(columns=['id', 'obs_id','day_obs','group_name' ,'seq_num', 'type', 'target','filter','zenith_angle','expos','ra','dec','skyangle'])

In [8]:
for count, info in enumerate(registry.queryDimensionRecords('exposure')):
    
    
    df_exposure.loc[count] = [info.id, info.obs_id, info.day_obs, info.group_name,info.seq_num, info.observation_type, info.target_name, info.physical_filter, info.zenith_angle, \
                             info.exposure_time,info.tracking_ra, info.tracking_dec, info.sky_angle]
    
    if count < 0:
        print("-----------------------------------------------------",count,"---------------------------------------------------------")
        print(info)
        print("\t id:                  ",info.id)
        print("\t day_obs:             ",info.day_obs)
        print("\t group_name:             ",info.group_name)
        print("\t seq_num:             ",info.seq_num)
        print("\t type-of-observation: ",info.observation_type)
        print("\t target:              ",info.target_name)

In [9]:
df_exposure

,id,obs_id,day_obs,group_name,seq_num,type,target,filter,zenith_angle,expos,ra,dec,skyangle
0,2021021600208,AT_O_20210216_000208,20210216,2021-02-17T03:35:45.035,208,science,HD 50896,empty~empty,24.314073,2.0,103.384002,-23.973448,-180.0
1,2021021600163,AT_O_20210216_000163,20210216,2021-02-17T00:50:15.536,163,science,HD 50896,RG610~empty,14.580611,3.0,103.404029,-23.92939,-208.621712
2,2021021600070,AT_O_20210216_000070,20210216,2021-02-16T20:39:31.417,70,bias,azel_target,empty~empty,None,0.0,None,None,None
3,2021021600173,AT_O_20210216_000173,20210216,2021-02-17T01:21:19.215,173,science,HD 50896,RG610~empty,8.82931,2.0,103.395986,-23.927038,-208.621712
4,2021021600001,AT_O_20210216_000001,20210216,2021-02-16T19:50:21.993,1,bias,azel_target,empty~empty,None,0.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21152,2022063000801,AT_O_20220630_000801,20220630,2022-07-01T09:23:29.769,801,science,AUXTEL_DRP_IMAGING:WFI-2026-4536_062,SDSSr~empty,36.396484,30.0,306.677395,-45.325215,359.998841
21153,2022063000802,AT_O_20220630_000802,20220630,2022-07-01T09:24:43.587,802,science,AUXTEL_DRP_IMAGING:WFI-2026-4536_063,SDSSr~empty,36.437127,30.0,306.811224,-45.325305,0.005404
21154,2022063000803,AT_O_20220630_000803,20220630,2022-07-01T09:24:43.587,803,science,AUXTEL_DRP_IMAGING:WFI-2026-4536_063,SDSSr~empty,36.530061,30.0,306.811146,-45.325195,359.99891
21155,2022063000804,AT_O_20220630_000804,20220630,2022-07-01T09:25:58.670,804,science,AUXTEL_DRP_IMAGING:WFI-2026-4536_064,SDSSr~empty,36.57364,30.0,306.944962,-45.325294,359.998843
21156,2022063000805,AT_O_20220630_000805,20220630,2022-07-01T09:25:58.670,805,science,AUXTEL_DRP_IMAGING:WFI-2026-4536_064,SDSSr~empty,36.666615,30.0,306.944896,-45.32522,359.998972

## Selection of Flats

In [10]:
df_flat = df_exposure[df_exposure.type == 'flat']

In [11]:
df_flat.sort_values(by="id",ascending=True,inplace=True)

/tmp/ipykernel_2899/2352331422.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_flat.sort_values(by="id",ascending=True,inplace=True)

In [12]:
df_flat.tail(60)

,id,obs_id,day_obs,group_name,seq_num,type,target,filter,zenith_angle,expos,ra,dec,skyangle
18268,2022060900036,AT_O_20220609_000036,20220609,2022-06-09T21:19:55.750,36,flat,FlatField position,BG40~empty,51.003493,6.00,None,None,None
18269,2022060900037,AT_O_20220609_000037,20220609,2022-06-09T21:19:55.750,37,flat,FlatField position,BG40~empty,51.0035,6.00,None,None,None
18270,2022060900038,AT_O_20220609_000038,20220609,2022-06-09T21:19:55.750,38,flat,FlatField position,BG40~empty,51.0035,6.00,None,None,None
18271,2022060900039,AT_O_20220609_000039,20220609,2022-06-09T21:19:55.750,39,flat,FlatField position,BG40~empty,51.0035,6.00,None,None,None
18272,2022060900040,AT_O_20220609_000040,20220609,2022-06-09T21:19:55.750,40,flat,FlatField position,BG40~empty,51.0035,6.00,None,None,None
18273,2022060900041,AT_O_20220609_000041,20220609,2022-06-09T21:19:55.750,41,flat,FlatField position,BG40~empty,51.003503,6.00,None,None,None
18274,2022060900042,AT_O_20220609_000042,20220609,2022-06-09T21:19:55.750,42,flat,FlatField position,BG40~empty,51.003503,6.00,None,None,None
18275,2022060900043,AT_O_20220609_000043,20220609,2022-06-09T21:19:55.750,43,flat,FlatField position,BG40~empty,51.003506,6.00,None,None,None
18276,2022060900044,AT_O_20220609_000044,20220609,2022-06-09T21:19:55.750,44,flat,FlatField position,BG40~empty,51.003504,6.00,None,None,None
18277,2022060900045,AT_O_20220609_000045,20220609,2022-06-09T21:21:58.370,45,flat,FlatField position,SDSSg~empty,51.003509,6.00,None,None,None
18278,2022060900046,AT_O_20220609_000046,20220609,2022-06-09T21:21:58.370,46,flat,FlatField position,SDSSg~empty,51.003513,6.00,None,None,None
18279,2022060900047,AT_O_20220609_000047,20220609,2022-06-09T21:21:58.370,47,flat,FlatField position,SDSSg~empty,51.003514,6.00,None,None,None
18280,2022060900048,AT_O_20220609_000048,20220609,2022-06-09T21:21:58.370,48,flat,FlatField position,SDSSg~empty,51.003515,6.00,None,None,None
18281,2022060900049,AT_O_20220609_000049,20220609,2022-06-09T21:21:58.370,49,flat,FlatField position,SDSSg~empty,51.003517,6.00,None,None,None
18282,2022060900050,AT_O_20220609_000050,20220609,2022-06-09T21:21:58.370,50,flat,FlatField position,SDSSg~empty,51.003518,6.00,None,None,None
18283,2022060900051,AT_O_20220609_000051,20220609,2022-06-09T21:21:58.370,51,flat,FlatField position,SDSSg~empty,51.003522,6.00,None,None,None
18284,2022060900052,AT_O_20220609_000052,20220609,2022-06-09T21:21:58.370,52,flat,FlatField position,SDSSg~empty,51.003518,6.00,None,None,None
18285,2022060900053,AT_O_20220609_000053,20220609,2022-06-09T21:21:58.370,53,flat,FlatField position,SDSSg~empty,51.00352,6.00,None,None,None
18286,2022060900054,AT_O_20220609_000054,20220609,2022-06-09T21:21:58.370,54,flat,FlatField position,SDSSg~empty,51.003523,6.00,None,None,None
19080,2022062800008,AT_O_20220628_000008,20220628,2022-06-28T22:21:22.970,8,flat,FlatField position,FELH0600~empty,50.999888,1.00,None,None,None
19081,2022062800009,AT_O_20220628_000009,20220628,2022-06-28T22:21:22.970,9,flat,FlatField position,FELH0600~empty,50.999885,1.00,None,None,None
19093,2022062800022,AT_O_20220628_000022,20220628,2022-06-28T22:28:50.376,22,flat,FlatField position,FELH0600~empty,50.999874,0.10,None,None,None
19094,2022062800023,AT_O_20220628_000023,20220628,2022-06-28T22:28:53.186,23,flat,FlatField position,FELH0600~empty,50.999869,0.10,None,None,None
19095,2022062800024,AT_O_20220628_000024,20220628,2022-06-28T22:28:55.862,24,flat,FlatField position,FELH0600~empty,50.999874,0.35,None,None,None
19096,2022062800025,AT_O_20220628_000025,20220628,2022-06-28T22:28:58.781,25,flat,FlatField position,FELH0600~empty,50.999873,0.35,None,None,None
19097,2022062800026,AT_O_20220628_000026,20220628,2022-06-28T22:29:01.696,26,flat,FlatField position,FELH0600~empty,50.99987,0.60,None,None,None
19098,2022062800027,AT_O_20220628_000027,20220628,2022-06-28T22:29:04.862,27,flat,FlatField position,FELH0600~empty,50.999872,0.60,None,None,None
19099,2022062800028,AT_O_20220628_000028,20220628,2022-06-28T22:29:08.024,28,flat,FlatField position,FELH0600~empty,50.999872,1.80,None,None,None
19100,2022062800029,AT_O_20220628_000029,20220628,2022-06-28T22:29:12.383,29,flat,FlatField position,FELH0600~empty,50.999871,1.80,None,None,None
19101,2022062800030,AT_O_20220628_000030,20220628,2022-06-28T22:29:16.740,30,flat,FlatField position,FELH0600~empty,50.999873,2.50,None,None,None
19102,2022062800031,AT_O_20220628_000031,20220628,2022-06-28T22:29:21.799,31,flat,FlatField position,FELH0600~empty,50.999873,2.50,None,None,None
19103,2022062800032,AT_O_20220628_000032,20220628,2022-06-28T22:29:26.862,32,flat,FlatField position,FELH0600~empty,50.999854,3.80,None,None,None
19104,2022062800033,AT_O_20220628_000033,20220628,2022-06-28T22:29:33.232,33,flat,FlatField position,FELH0600~empty,50.99985,3.80,None,None,None
19105,2022062800034,AT_O_20220628_000034,20220628,2022-06-28T22:29:39.596,34,flat,FlatField position,FELH0600~empty,50.99985,5.60,None,None,None
19106,2022062800035,AT_O_20220628_000035,20220628,2022-06-28T22:29:47.756,35,flat,FlatField position,FELH0600~empty,50.999848,5.60,None,None,None
19851,2022062900018,AT_O_20220629_000018,20220629,2022-06-29T21:25:27.421,18,flat,FlatField position,SDSSr~empty,50.999766,0.10,None,None,None
19852,2022062900019,AT_O_20220629_000019,20220629,2022-06-29T21:25:30.246,19,flat,FlatField position,SDSSr~empty,50.999765,0.10,None,None,None
19853,2022062900020,AT_O_20220629_000020,20220629,2022-06-29T21:25:32.911,20,flat,FlatField position,SDSSr~empty,50.999763,0.35,None,None,None
19854,2022062900022,AT_O_20220629_000022,20220629,2022-06-29T21:25:38.733,22,flat,FlatField position,SDSSr~empty,50.999764,0.60,None,None,None
19855,2022062900023,AT_O_20220629_000023,20220629,2022-06-29T21:25:41.899,23,flat,FlatField position,SDSSr~empty,50.999766,0.60,None,None,None
19856,2022062900024,AT_O_20220629_000024,20220629,2022-06-29T21:25:45.055,24,flat,FlatField position,SDSSr~empty,50.999762,1.80,None,None,None
19857,2022062900025,AT_O_20220629_000025,20220629,2022-06-29T21:25:49.419,25,flat,FlatField position,SDSSr~empty,50.999763,1.80,None,None,None
19858,2022062900026,AT_O_20220629_000026,20220629,2022-06-29T21:25:53.769,26,flat,FlatField position,SDSSr~empty,50.999766,2.50,None,None,None
19861,2022062900029,AT_O_20220629_000029,20220629,2022-06-29T21:26:10.259,29,flat,FlatField position,SDSSr~empty,50.999765,3.80,None,None,None
19862,2022062900030,AT_O_20220629_000030,20220629,2022-06-29T21:26:16.618,30,flat,FlatField position,SDSSr~empty,50.999765,5.60,None,None,None
19863,2022062900031,AT_O_20220629_000031,20220629,2022-06-29T21:26:24.780,31,flat,FlatField position,SDSSr~empty,50.999765,5.60,None,None,None
20392,2022063000015,AT_O_20220630_000015,20220630,2022-06-30T22:08:06.628,15,flat,FlatField position,SDSSr~holo4_003,50.999903,0.10,None,None,None
19813,2022063000016,AT_O_20220630_000016,20220630,2022-06-30T22:08:09.436,16,flat,FlatField position,SDSSr~holo4_003,50.999901,0.10,None,None,None
20393,2022063000017,AT_O_20220630_000017,20220630,2022-06-30T22:08:12.096,17,flat,FlatField position,SDSSr~holo4_003,50.999901,0.35,None,None,None
19814,2022063000018,AT_O_20220630_000018,20220630,2022-06-30T22:08:15.000,18,flat,FlatField position,SDSSr~holo4_003,50.999902,0.35,None,None,None
20394,2022063000019,AT_O_20220630_000019,20220630,2022-06-30T22:08:17.917,19,flat,FlatField position,SDSSr~holo4_003,50.9999,0.60,None,None,None
19815,2022063000020,AT_O_20220630_000020,20220630,2022-06-30T22:08:21.069,20,flat,FlatField position,SDSSr~holo4_003,50.999903,0.60,None,None,None
20395,2022063000021,AT_O_20220630_000021,20220630,2022-06-30T22:08:24.226,21,flat,FlatField position,SDSSr~holo4_003,50.999903,1.80,None,None,None
19816,2022063000022,AT_O_20220630_000022,20220630,2022-06-30T22:08:28.582,22,flat,FlatField position,SDSSr~holo4_003,50.999901,1.80,None,None,None
20396,2022063000023,AT_O_20220630_000023,20220630,2022-06-30T22:08:32.943,23,flat,FlatField position,SDSSr~holo4_003,50.999899,2.50,None,None,None
19817,2022063000024,AT_O_20220630_000024,20220630,2022-06-30T22:08:38.011,24,flat,FlatField position,SDSSr~holo4_003,50.9999,2.50,None,None,None
20397,2022063000025,AT_O_20220630_000025,20220630,2022-06-30T22:08:43.071,25,flat,FlatField position,SDSSr~holo4_003,50.999901,3.80,None,None,None
19818,2022063000026,AT_O_20220630_000026,20220630,2022-06-30T22:08:49.428,26,flat,FlatField position,SDSSr~holo4_003,50.9999,3.80,None,None,None
20398,2022063000027,AT_O_20220630_000027,20220630,2022-06-30T22:08:55.798,27,flat,FlatField position,SDSSr~holo4_003,50.999899,5.60,None,None,None
19819,2022063000028,AT_O_20220630_000028,20220630,2022-06-30T22:09:03.952,28,flat,FlatField position,SDSSr~holo4_003,50.9999,5.60,None,None,None

In [13]:
df_flat.day_obs.unique()

array([20210216, 20210217, 20210218, 20210311, 20210608, 20210609,
       20210707, 20210708, 20210907, 20210908, 20210909, 20211005,
       20211006, 20211007, 20211102, 20211104, 20220215, 20220216,
       20220217, 20220315, 20220316, 20220317, 20220502, 20220503,
       20220504, 20220524, 20220607, 20220608, 20220609, 20220628,
       20220629, 20220630])

## Selection of date

### Add those

20220504 - Not existing

In [14]:
date_sel = 20220609

In [15]:
df_flat_selected = df_flat[df_flat.day_obs == date_sel ]

In [16]:
len(df_flat_selected)

30

# List of filters

In [17]:
list_of_filters = df_flat_selected['filter'].unique()
list_of_filters

array(['FELH0600~empty', 'BG40~empty', 'SDSSg~empty'], dtype=object)

In [18]:
selected_filters = []
for filt in list_of_filters:
    #flag_sel = (filt.find('holo4') != -1) or (filt.find('ronchi90lpmm') != -1) or (filt.find('ronchi170lpmm') != -1)
    #flag_sel = (filt.find('holo4') != -1) 
    #flag_sel = (filt.find('ronchi170') != -1) 
    flag_sel = True
    if flag_sel:
        selected_filters.append(filt) 
selected_filters = np.array(selected_filters)
selected_filters

array(['FELH0600~empty', 'BG40~empty', 'SDSSg~empty'], dtype='<U14')

## Selection of filter

- But now we have a loop on filters

In [19]:
#idx_sel_filt = 0
#selected_filter = selected_filters[0]
#selected_filter

## Final selection of exposure

- loop on selected filters

In [20]:
pd.set_option('display.max_rows', None)

In [21]:
all_def_flat_selected_final = []

for selected_filter in selected_filters:

    print(selected_filter)
    df_flat_selected_final = df_flat_selected[df_flat_selected["filter"] ==  selected_filter]
    
    #print(df_science_selected_final)
    all_def_flat_selected_final.append(df_flat_selected_final.copy())
    
    df = df_flat_selected_final
    df_sel = df[['day_obs', 'seq_num']]
    
    
    NN = len(df)
    
    if NN>0:
        # build the line
        
        df_sel['line'] = df_sel.apply(lambda row: str(row['day_obs'])  + " " + str(row['seq_num']),axis = 1)
    
    
         # prepare output
        filename_out = "visitflat_"+ str(date_sel) + "_filt_" + selected_filter.replace('~','-') + ".list"
        print(filename_out)
        
        df_out = df_sel[["line"]]
        df_out.to_csv(filename_out, index=False, header=None)

/tmp/ipykernel_2899/257492132.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sel['line'] = df_sel.apply(lambda row: str(row['day_obs'])  + " " + str(row['seq_num']),axis = 1)

FELH0600~empty
visitflat_20220609_filt_FELH0600-empty.list
BG40~empty
visitflat_20220609_filt_BG40-empty.list
SDSSg~empty
visitflat_20220609_filt_SDSSg-empty.list

/tmp/ipykernel_2899/257492132.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sel['line'] = df_sel.apply(lambda row: str(row['day_obs'])  + " " + str(row['seq_num']),axis = 1)
/tmp/ipykernel_2899/257492132.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sel['line'] = df_sel.apply(lambda row: str(row['day_obs'])  + " " + str(row['seq_num']),axis = 1)

In [22]:
len(all_def_flat_selected_final)

3

In [23]:
all_def_flat_selected_final[0]

,id,obs_id,day_obs,group_name,seq_num,type,target,filter,zenith_angle,expos,ra,dec,skyangle
18257,2022060900025,AT_O_20220609_000025,20220609,2022-06-09T21:14:39.432,25,flat,FlatField position,FELH0600~empty,51.003452,6.0,None,None,None
18258,2022060900026,AT_O_20220609_000026,20220609,2022-06-09T21:14:39.432,26,flat,FlatField position,FELH0600~empty,51.003451,6.0,None,None,None
18259,2022060900027,AT_O_20220609_000027,20220609,2022-06-09T21:14:39.432,27,flat,FlatField position,FELH0600~empty,51.003453,6.0,None,None,None
18260,2022060900028,AT_O_20220609_000028,20220609,2022-06-09T21:14:39.432,28,flat,FlatField position,FELH0600~empty,51.003452,6.0,None,None,None
18261,2022060900029,AT_O_20220609_000029,20220609,2022-06-09T21:14:39.432,29,flat,FlatField position,FELH0600~empty,51.003455,6.0,None,None,None
18262,2022060900030,AT_O_20220609_000030,20220609,2022-06-09T21:14:39.432,30,flat,FlatField position,FELH0600~empty,51.003456,6.0,None,None,None
18263,2022060900031,AT_O_20220609_000031,20220609,2022-06-09T21:14:39.432,31,flat,FlatField position,FELH0600~empty,51.003456,6.0,None,None,None
18264,2022060900032,AT_O_20220609_000032,20220609,2022-06-09T21:14:39.432,32,flat,FlatField position,FELH0600~empty,51.003458,6.0,None,None,None
18265,2022060900033,AT_O_20220609_000033,20220609,2022-06-09T21:14:39.432,33,flat,FlatField position,FELH0600~empty,51.003461,6.0,None,None,None
18266,2022060900034,AT_O_20220609_000034,20220609,2022-06-09T21:14:39.432,34,flat,FlatField position,FELH0600~empty,51.003461,6.0,None,None,None

In [24]:
all_def_flat_selected_final[1]

,id,obs_id,day_obs,group_name,seq_num,type,target,filter,zenith_angle,expos,ra,dec,skyangle
18267,2022060900035,AT_O_20220609_000035,20220609,2022-06-09T21:19:55.750,35,flat,FlatField position,BG40~empty,51.003498,6.0,None,None,None
18268,2022060900036,AT_O_20220609_000036,20220609,2022-06-09T21:19:55.750,36,flat,FlatField position,BG40~empty,51.003493,6.0,None,None,None
18269,2022060900037,AT_O_20220609_000037,20220609,2022-06-09T21:19:55.750,37,flat,FlatField position,BG40~empty,51.0035,6.0,None,None,None
18270,2022060900038,AT_O_20220609_000038,20220609,2022-06-09T21:19:55.750,38,flat,FlatField position,BG40~empty,51.0035,6.0,None,None,None
18271,2022060900039,AT_O_20220609_000039,20220609,2022-06-09T21:19:55.750,39,flat,FlatField position,BG40~empty,51.0035,6.0,None,None,None
18272,2022060900040,AT_O_20220609_000040,20220609,2022-06-09T21:19:55.750,40,flat,FlatField position,BG40~empty,51.0035,6.0,None,None,None
18273,2022060900041,AT_O_20220609_000041,20220609,2022-06-09T21:19:55.750,41,flat,FlatField position,BG40~empty,51.003503,6.0,None,None,None
18274,2022060900042,AT_O_20220609_000042,20220609,2022-06-09T21:19:55.750,42,flat,FlatField position,BG40~empty,51.003503,6.0,None,None,None
18275,2022060900043,AT_O_20220609_000043,20220609,2022-06-09T21:19:55.750,43,flat,FlatField position,BG40~empty,51.003506,6.0,None,None,None
18276,2022060900044,AT_O_20220609_000044,20220609,2022-06-09T21:19:55.750,44,flat,FlatField position,BG40~empty,51.003504,6.0,None,None,None

In [25]:
all_def_flat_selected_final[2]

,id,obs_id,day_obs,group_name,seq_num,type,target,filter,zenith_angle,expos,ra,dec,skyangle
18277,2022060900045,AT_O_20220609_000045,20220609,2022-06-09T21:21:58.370,45,flat,FlatField position,SDSSg~empty,51.003509,6.0,None,None,None
18278,2022060900046,AT_O_20220609_000046,20220609,2022-06-09T21:21:58.370,46,flat,FlatField position,SDSSg~empty,51.003513,6.0,None,None,None
18279,2022060900047,AT_O_20220609_000047,20220609,2022-06-09T21:21:58.370,47,flat,FlatField position,SDSSg~empty,51.003514,6.0,None,None,None
18280,2022060900048,AT_O_20220609_000048,20220609,2022-06-09T21:21:58.370,48,flat,FlatField position,SDSSg~empty,51.003515,6.0,None,None,None
18281,2022060900049,AT_O_20220609_000049,20220609,2022-06-09T21:21:58.370,49,flat,FlatField position,SDSSg~empty,51.003517,6.0,None,None,None
18282,2022060900050,AT_O_20220609_000050,20220609,2022-06-09T21:21:58.370,50,flat,FlatField position,SDSSg~empty,51.003518,6.0,None,None,None
18283,2022060900051,AT_O_20220609_000051,20220609,2022-06-09T21:21:58.370,51,flat,FlatField position,SDSSg~empty,51.003522,6.0,None,None,None
18284,2022060900052,AT_O_20220609_000052,20220609,2022-06-09T21:21:58.370,52,flat,FlatField position,SDSSg~empty,51.003518,6.0,None,None,None
18285,2022060900053,AT_O_20220609_000053,20220609,2022-06-09T21:21:58.370,53,flat,FlatField position,SDSSg~empty,51.00352,6.0,None,None,None
18286,2022060900054,AT_O_20220609_000054,20220609,2022-06-09T21:21:58.370,54,flat,FlatField position,SDSSg~empty,51.003523,6.0,None,None,None

In [26]:
all_def_flat_selected_final[3]

IndexError: list index out of range

In [ ]:
all_def_flat_selected_final[4]