# List of Exposures Flats


- work with Weakly_2022_09
- use jupyter kernel LSST



- author : Sylvie Dagoret-Campagne
- affiliation : IJCLab
- creation date : 2022/03/21

In [1]:
! eups list -s | grep LOCAL

atmospec              LOCAL:/sps/lsst/groups/auxtel/softs/shared/auxteldm_gen3/repos/w_2022_09/atmospec 	setup
eups                  LOCAL:/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2022_09/conda/envs/lsst-scipipe-2.0.0/eups 	setup
rapid_analysis        LOCAL:/sps/lsst/groups/auxtel/softs/shared/auxteldm_gen3/repos/w_2022_09/rapid_analysis 	setup

In [2]:
! echo $IMAGE_DESCRIPTION
! eups list -s lsst_distrib

   g64fc59b30a+e1dba0a6f6 	w_latest w_2022_09 current setup

In [3]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
from matplotlib.colors import LogNorm

from mpl_toolkits.axes_grid1 import make_axes_locatable

import matplotlib.ticker                         # here's where the formatter is
from matplotlib.ticker import (MultipleLocator, FormatStrFormatter,
                               AutoMinorLocator)

from astropy.io import fits

In [4]:
import lsst.afw.display as afwDisplay
afwDisplay.setDefaultBackend('matplotlib')

In [5]:
import lsst.daf.butler as dafButler

In [6]:
repo = '/sps/lsst/groups/auxtel/softs/shared/auxteldm_gen3/data/butler.yaml'
butler = dafButler.Butler(repo)
registry = butler.registry

## List of Exposures

In [7]:
df_exposure = pd.DataFrame(columns=['id', 'obs_id','day_obs', 'seq_num', 'type', 'target','filter','zenith_angle','ra','dec','skyangle'])

In [8]:
for count, info in enumerate(registry.queryDimensionRecords('exposure')):
    
    
    df_exposure.loc[count] = [info.id, info.obs_id, info.day_obs, info.seq_num, info.observation_type, info.target_name, info.physical_filter, info.zenith_angle, \
                             info.tracking_ra, info.tracking_dec, info.sky_angle]
    
    if count < 2:
        print("-----------------------------------------------------",count,"---------------------------------------------------------")
        print(info)
        print("\t id:                  ",info.id)
        print("\t day_obs:             ",info.day_obs)
        print("\t seq_num:             ",info.seq_num)
        print("\t type-of-observation: ",info.observation_type)
        print("\t target:              ",info.target_name)

----------------------------------------------------- 0 ---------------------------------------------------------
exposure:
  instrument: 'LATISS'
  id: 2021021600208
  physical_filter: 'empty~empty'
  obs_id: 'AT_O_20210216_000208'
  exposure_time: 2.0
  dark_time: 2.33517265319824
  observation_type: 'science'
  observation_reason: 'science'
  day_obs: 20210216
  seq_num: 208
  group_name: '2021-02-17T03:35:45.035'
  group_id: 1934625450350000
  target_name: 'HD 50896'
  science_program: 'unknown'
  tracking_ra: 103.384001783548
  tracking_dec: -23.9734478006315
  sky_angle: -180.0
  zenith_angle: 24.314073266185005
  timespan: Timespan(begin=astropy.time.Time('2021-02-17 03:35:45.295446', scale='tai', format='iso'), end=astropy.time.Time('2021-02-17 03:35:47.540000', scale='tai', format='iso'))
	 id:                   2021021600208
	 day_obs:              20210216
	 seq_num:              208
	 type-of-observation:  science
	 target:               HD 50896
----------------------------------------------------- 1 ---------------------------------------------------------
exposure:
  instrument: 'LATISS'
  id: 2021021600163
  physical_filter: 'RG610~empty'
  obs_id: 'AT_O_20210216_000163'
  exposure_time: 3.0
  dark_time: 3.3251359462738
  observation_type: 'science'
  observation_reason: 'science'
  day_obs: 20210216
  seq_num: 163
  group_name: '2021-02-17T00:50:15.536'
  group_id: 1934526155360000
  target_name: 'HD 50896'
  science_program: 'unknown'
  tracking_ra: 103.404029472597
  tracking_dec: -23.9293904683577
  sky_angle: -208.6217120790572
  zenith_angle: 14.580610783508703
  timespan: Timespan(begin=astropy.time.Time('2021-02-17 00:50:15.703984', scale='tai', format='iso'), end=astropy.time.Time('2021-02-17 00:50:18.939000', scale='tai', format='iso'))
	 id:                   2021021600163
	 day_obs:              20210216
	 seq_num:              163
	 type-of-observation:  science
	 target:               HD 50896

In [9]:
df_exposure

,id,obs_id,day_obs,seq_num,type,target,filter,zenith_angle,ra,dec,skyangle
0,2021021600208,AT_O_20210216_000208,20210216,208,science,HD 50896,empty~empty,24.314073,103.384002,-23.973448,-180.0
1,2021021600163,AT_O_20210216_000163,20210216,163,science,HD 50896,RG610~empty,14.580611,103.404029,-23.92939,-208.621712
2,2021021600070,AT_O_20210216_000070,20210216,70,bias,azel_target,empty~empty,None,None,None,None
3,2021021600173,AT_O_20210216_000173,20210216,173,science,HD 50896,RG610~empty,8.82931,103.395986,-23.927038,-208.621712
4,2021021600001,AT_O_20210216_000001,20210216,1,bias,azel_target,empty~empty,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
12869,2022031500091,AT_O_20220315_000091,20220315,91,flat,FlatField position,SDSSr~empty,51.333026,None,None,None
12870,2022031500031,AT_O_20220315_000031,20220315,31,bias,FlatField position,empty~empty,None,None,None,None
12871,2022031500109,AT_O_20220315_000109,20220315,109,flat,FlatField position,SDSSg~empty,51.333308,None,None,None
12872,2022031500068,AT_O_20220315_000068,20220315,68,bias,FlatField position,empty~empty,None,None,None,None
12873,2022031500062,AT_O_20220315_000062,20220315,62,bias,FlatField position,empty~empty,None,None,None,None

## Selection of flats

In [10]:
df_flat = df_exposure[df_exposure.type == 'flat']

In [11]:
df_flat.sort_values(by="day_obs",ascending=True,inplace=True)

/tmp/ipykernel_6659/2047437805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_flat.sort_values(by="day_obs",ascending=True,inplace=True)

In [12]:
df_flat.tail(50)

,id,obs_id,day_obs,seq_num,type,target,filter,zenith_angle,ra,dec,skyangle
11345,2022021600061,AT_O_20220216_000061,20220216,61,flat,FlatField position,SDSSr~empty,51.002879,None,None,None
11338,2022021600057,AT_O_20220216_000057,20220216,57,flat,FlatField position,SDSSr~empty,51.002885,None,None,None
11317,2022021600063,AT_O_20220216_000063,20220216,63,flat,FlatField position,SDSSr~empty,51.002879,None,None,None
11279,2022021600050,AT_O_20220216_000050,20220216,50,flat,FlatField position,SDSSr~empty,51.002894,None,None,None
11700,2022021600051,AT_O_20220216_000051,20220216,51,flat,FlatField position,SDSSr~empty,51.002879,None,None,None
12316,2022021700050,AT_O_20220217_000050,20220217,50,flat,FlatField position,SDSSr~empty,51.000085,None,None,None
12346,2022021700004,AT_O_20220217_000004,20220217,4,flat,FlatField position,SDSSr~empty,51.000073,None,None,None
12350,2022021700064,AT_O_20220217_000064,20220217,64,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
12375,2022021700063,AT_O_20220217_000063,20220217,63,flat,FlatField position,SDSSr~empty,51.000088,None,None,None
12742,2022021700045,AT_O_20220217_000045,20220217,45,flat,FlatField position,SDSSr~empty,51.000086,None,None,None
12617,2022021700053,AT_O_20220217_000053,20220217,53,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
12299,2022021700061,AT_O_20220217_000061,20220217,61,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
12760,2022021700046,AT_O_20220217_000046,20220217,46,flat,FlatField position,SDSSr~empty,51.000089,None,None,None
12452,2022021700060,AT_O_20220217_000060,20220217,60,flat,FlatField position,SDSSr~empty,51.000089,None,None,None
12218,2022021700049,AT_O_20220217_000049,20220217,49,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
12531,2022021700059,AT_O_20220217_000059,20220217,59,flat,FlatField position,SDSSr~empty,51.000088,None,None,None
12053,2022021700062,AT_O_20220217_000062,20220217,62,flat,FlatField position,SDSSr~empty,51.000088,None,None,None
12040,2022021700058,AT_O_20220217_000058,20220217,58,flat,FlatField position,SDSSr~empty,51.000088,None,None,None
12036,2022021700055,AT_O_20220217_000055,20220217,55,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
12024,2022021700051,AT_O_20220217_000051,20220217,51,flat,FlatField position,SDSSr~empty,51.000086,None,None,None
12014,2022021700054,AT_O_20220217_000054,20220217,54,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
12010,2022021700047,AT_O_20220217_000047,20220217,47,flat,FlatField position,SDSSr~empty,51.000086,None,None,None
12009,2022021700048,AT_O_20220217_000048,20220217,48,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
11998,2022021700052,AT_O_20220217_000052,20220217,52,flat,FlatField position,SDSSr~empty,51.000087,None,None,None
11997,2022021700056,AT_O_20220217_000056,20220217,56,flat,FlatField position,SDSSr~empty,51.000086,None,None,None
12204,2022021700057,AT_O_20220217_000057,20220217,57,flat,FlatField position,SDSSr~empty,51.000086,None,None,None
12834,2022031500098,AT_O_20220315_000098,20220315,98,flat,FlatField position,SDSSr~empty,51.333132,None,None,None
12835,2022031500105,AT_O_20220315_000105,20220315,105,flat,FlatField position,SDSSg~empty,51.333304,None,None,None
12841,2022031500111,AT_O_20220315_000111,20220315,111,flat,FlatField position,SDSSg~empty,51.333314,None,None,None
12853,2022031500103,AT_O_20220315_000103,20220315,103,flat,FlatField position,SDSSg~empty,51.333282,None,None,None
12864,2022031500100,AT_O_20220315_000100,20220315,100,flat,FlatField position,SDSSr~empty,51.333134,None,None,None
12857,2022031500107,AT_O_20220315_000107,20220315,107,flat,FlatField position,SDSSg~empty,51.333308,None,None,None
12860,2022031500108,AT_O_20220315_000108,20220315,108,flat,FlatField position,SDSSg~empty,51.33331,None,None,None
12833,2022031500112,AT_O_20220315_000112,20220315,112,flat,FlatField position,SDSSg~empty,51.333314,None,None,None
12868,2022031500092,AT_O_20220315_000092,20220315,92,flat,FlatField position,SDSSg~empty,51.333103,None,None,None
12854,2022031500099,AT_O_20220315_000099,20220315,99,flat,FlatField position,SDSSr~empty,51.333136,None,None,None
12816,2022031500095,AT_O_20220315_000095,20220315,95,flat,FlatField position,SDSSr~empty,51.333131,None,None,None
12797,2022031500102,AT_O_20220315_000102,20220315,102,flat,FlatField position,SDSSr~empty,51.333136,None,None,None
12807,2022031500096,AT_O_20220315_000096,20220315,96,flat,FlatField position,SDSSr~empty,51.333132,None,None,None
12805,2022031500094,AT_O_20220315_000094,20220315,94,flat,FlatField position,SDSSr~empty,51.333128,None,None,None
12800,2022031500113,AT_O_20220315_000113,20220315,113,flat,FlatField position,SDSSg~empty,51.333316,None,None,None
12785,2022031500101,AT_O_20220315_000101,20220315,101,flat,FlatField position,SDSSr~empty,51.333136,None,None,None
12784,2022031500097,AT_O_20220315_000097,20220315,97,flat,FlatField position,SDSSr~empty,51.333131,None,None,None
12777,2022031500104,AT_O_20220315_000104,20220315,104,flat,FlatField position,SDSSg~empty,51.333288,None,None,None
12771,2022031500114,AT_O_20220315_000114,20220315,114,flat,FlatField position,SDSSg~empty,51.333318,None,None,None
12767,2022031500110,AT_O_20220315_000110,20220315,110,flat,FlatField position,SDSSg~empty,51.333312,None,None,None
12764,2022031500093,AT_O_20220315_000093,20220315,93,flat,FlatField position,SDSSr~empty,51.333129,None,None,None
12869,2022031500091,AT_O_20220315_000091,20220315,91,flat,FlatField position,SDSSr~empty,51.333026,None,None,None
12808,2022031500106,AT_O_20220315_000106,20220315,106,flat,FlatField position,SDSSg~empty,51.333304,None,None,None
12871,2022031500109,AT_O_20220315_000109,20220315,109,flat,FlatField position,SDSSg~empty,51.333308,None,None,None

# List of dates

In [13]:
list_of_dates_flats = df_flat['day_obs'].unique() 
list_of_dates_flats

array([20210216, 20210217, 20210218, 20210311, 20210608, 20210609,
       20210707, 20210708, 20210907, 20210908, 20210909, 20211005,
       20211006, 20211007, 20211102, 20211104, 20220215, 20220216,
       20220217, 20220315])

# List of filters

In [14]:
list_of_filters = df_flat['filter'].unique()
list_of_filters

array(['empty~empty', 'RG610~empty', 'empty~holo4_003', 'BG40~empty',
       'FELH0600~empty', 'SDSSg~empty', 'SDSSr~empty'], dtype=object)