# Build filelist from registry.sqlite for flats


- author : Sylvie Dagoret-Campagne
- affiliation : IJCLab/IN2P3/CNRS
- creation date : January 18th 2022
- update : February 26th 2022
- update March 1st 2022 : change format of output file


- purpose create ascii files with exposure identifier in order to call DM-Stack pipeline

In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import pandas as pd

import sqlite3

In [2]:
def read_sqlite(dbfile):
    import sqlite3
    from pandas import read_sql_query, read_sql_table

    with sqlite3.connect(dbfile) as dbcon:
        tables = list(read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", dbcon)['name'])
        out = {tbl : read_sql_query(f"SELECT * from {tbl}", dbcon) for tbl in tables}

    return out

## Configuration

In [3]:
# database file
database_file = "registry.sqlite3"

## Read DB

### Guess of list of tables in a Dictionnary

In [4]:
dict_db = read_sqlite(database_file)

In [5]:
dict_db.keys()

dict_keys(['raw', 'sqlite_sequence', 'raw_visit'])

### Put selected table in a pandas dataframe

In [6]:
dat = sqlite3.connect(database_file)

In [7]:
query = dat.execute("SELECT * From raw")

In [8]:
cols = [column[0] for column in query.description]

In [9]:
results= pd.DataFrame.from_records(data = query.fetchall(), columns = cols)

In [10]:
results

,id,dayObs,seqNum,visit,detector,detectorName,filter,dateObs,date,expTime,object,imageType,wavelength,expGroup,obsid,expId
0,1,2021-06-08,1,2031133798900000,0,S00,RG610~holo4_003,2021-06-08T20:23:00.082,2021-06-08T20:23:00.082,0.0,azel_target,BIAS,-666,2021-06-08T20:22:59.890,AT_O_20210608_000001,2021060800001
1,2,2021-06-08,2,2031134348450000,0,S00,RG610~holo4_003,2021-06-08T20:23:55.021,2021-06-08T20:23:55.021,0.0,azel_target,BIAS,-666,2021-06-08T20:23:54.845,AT_O_20210608_000002,2021060800002
2,3,2021-06-08,3,2031134393460000,0,S00,RG610~holo4_003,2021-06-08T20:23:59.516,2021-06-08T20:23:59.516,0.0,azel_target,BIAS,-666,2021-06-08T20:23:59.346,AT_O_20210608_000003,2021060800003
3,4,2021-06-08,4,2031134438450000,0,S00,RG610~holo4_003,2021-06-08T20:24:04.019,2021-06-08T20:24:04.019,0.0,azel_target,BIAS,-666,2021-06-08T20:24:03.845,AT_O_20210608_000004,2021060800004
4,5,2021-06-08,5,2031134483610000,0,S00,RG610~holo4_003,2021-06-08T20:24:08.527,2021-06-08T20:24:08.527,0.0,azel_target,BIAS,-666,2021-06-08T20:24:08.361,AT_O_20210608_000005,2021060800005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,12756,2022-02-17,765,2251058140450000,0,S00,SDSSg~empty,2022-02-18T09:25:53.560,2022-02-18T09:25:53.560,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:23:34.045,AT_O_20220217_000765,2022021700765
12756,12757,2022-02-17,766,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:26:52.861,2022-02-18T09:26:52.861,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000766,2022021700766
12757,12758,2022-02-17,767,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:27:25.852,2022-02-18T09:27:25.852,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000767,2022021700767
12758,12759,2022-02-17,768,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:22.143,2022-02-18T09:28:22.143,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000768,2022021700768
12759,12760,2022-02-17,769,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:55.127,2022-02-18T09:28:55.127,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000769,2022021700769

## sort according day and time

In [11]:
results_sorted = results.sort_values(["dayObs", "seqNum"], ascending=True)

In [12]:
results_sorted

,id,dayObs,seqNum,visit,detector,detectorName,filter,dateObs,date,expTime,object,imageType,wavelength,expGroup,obsid,expId
8687,8688,2021-02-16,1,1934346219930000,0,S00,empty~empty,2021-02-16T19:50:22.184,2021-02-16T19:50:22.184,0.0,azel_target,BIAS,-666,2021-02-16T19:50:21.993,AT_O_20210216_000001,2021021600001
8688,8689,2021-02-16,2,1934362834080000,0,S00,empty~empty,2021-02-16T20:18:03.588,2021-02-16T20:18:03.588,0.0,azel_target,BIAS,-666,2021-02-16T20:18:03.408,AT_O_20210216_000002,2021021600002
8689,8690,2021-02-16,3,1934362963860000,0,S00,empty~empty,2021-02-16T20:18:16.563,2021-02-16T20:18:16.563,0.0,azel_target,BIAS,-666,2021-02-16T20:18:16.386,AT_O_20210216_000003,2021021600003
8690,8691,2021-02-16,4,1934363094110000,0,S00,empty~empty,2021-02-16T20:18:29.581,2021-02-16T20:18:29.581,0.0,azel_target,BIAS,-666,2021-02-16T20:18:29.411,AT_O_20210216_000004,2021021600004
8691,8692,2021-02-16,5,1934363223760000,0,S00,empty~empty,2021-02-16T20:18:42.546,2021-02-16T20:18:42.546,0.0,azel_target,BIAS,-666,2021-02-16T20:18:42.376,AT_O_20210216_000005,2021021600005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,12756,2022-02-17,765,2251058140450000,0,S00,SDSSg~empty,2022-02-18T09:25:53.560,2022-02-18T09:25:53.560,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:23:34.045,AT_O_20220217_000765,2022021700765
12756,12757,2022-02-17,766,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:26:52.861,2022-02-18T09:26:52.861,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000766,2022021700766
12757,12758,2022-02-17,767,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:27:25.852,2022-02-18T09:27:25.852,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000767,2022021700767
12758,12759,2022-02-17,768,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:22.143,2022-02-18T09:28:22.143,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000768,2022021700768
12759,12760,2022-02-17,769,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:55.127,2022-02-18T09:28:55.127,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000769,2022021700769

## imageType

In [13]:
list_of_imgtype = results_sorted['imageType'].unique()
list_of_imgtype

array(['BIAS', 'FLAT', 'SKYEXP', 'ENGTEST', 'DARK'], dtype=object)

In [14]:
def isflat(row):
    #print(row["filter"])
    if str(row["imageType"]) == "FLAT":
        return True
    
    else:
        return False

## Select flats

In [15]:
results_sorted["selected"] = results_sorted.apply(isflat,axis=1)

In [16]:
results_selected = results_sorted[results_sorted.selected] 
results_selected

,id,dayObs,seqNum,visit,detector,detectorName,filter,dateObs,date,expTime,object,imageType,wavelength,expGroup,obsid,expId,selected
8788,8789,2021-02-16,102,1934390234390000,0,S00,RG610~empty,2021-02-16T21:03:45.207,2021-02-16T21:03:45.207,2.0,FlatField position,FLAT,-666,2021-02-16T21:03:43.439,AT_O_20210216_000102,2021021600102,True
8789,8790,2021-02-16,103,1934390234390000,0,S00,RG610~empty,2021-02-16T21:03:49.790,2021-02-16T21:03:49.790,2.0,FlatField position,FLAT,-666,2021-02-16T21:03:43.439,AT_O_20210216_000103,2021021600103,True
8790,8791,2021-02-16,104,1934390234390000,0,S00,RG610~empty,2021-02-16T21:03:54.374,2021-02-16T21:03:54.374,2.0,FlatField position,FLAT,-666,2021-02-16T21:03:43.439,AT_O_20210216_000104,2021021600104,True
8791,8792,2021-02-16,105,1934390234390000,0,S00,RG610~empty,2021-02-16T21:03:58.958,2021-02-16T21:03:58.958,2.0,FlatField position,FLAT,-666,2021-02-16T21:03:43.439,AT_O_20210216_000105,2021021600105,True
8792,8793,2021-02-16,106,1934390234390000,0,S00,RG610~empty,2021-02-16T21:04:03.527,2021-02-16T21:04:03.527,2.0,FlatField position,FLAT,-666,2021-02-16T21:03:43.439,AT_O_20210216_000106,2021021600106,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12050,12051,2022-02-17,60,2250627582120000,0,S00,SDSSr~empty,2022-02-17T21:25:58.220,2022-02-17T21:25:58.220,2.0,FlatField position,FLAT,-666,2022-02-17T21:25:58.212,AT_O_20220217_000060,2022021700060,True
12051,12052,2022-02-17,61,2250627628310000,0,S00,SDSSr~empty,2022-02-17T21:26:02.841,2022-02-17T21:26:02.841,2.0,FlatField position,FLAT,-666,2022-02-17T21:26:02.831,AT_O_20220217_000061,2022021700061,True
12052,12053,2022-02-17,62,2250627674510000,0,S00,SDSSr~empty,2022-02-17T21:26:07.466,2022-02-17T21:26:07.466,2.0,FlatField position,FLAT,-666,2022-02-17T21:26:07.451,AT_O_20220217_000062,2022021700062,True
12053,12054,2022-02-17,63,2250627720960000,0,S00,SDSSr~empty,2022-02-17T21:26:12.108,2022-02-17T21:26:12.108,2.0,FlatField position,FLAT,-666,2022-02-17T21:26:12.096,AT_O_20220217_000063,2022021700063,True
12054,12055,2022-02-17,64,2250627767130000,0,S00,SDSSr~empty,2022-02-17T21:26:16.722,2022-02-17T21:26:16.722,2.0,FlatField position,FLAT,-666,2022-02-17T21:26:16.713,AT_O_20220217_000064,2022021700064,True

## dates of flats

In [17]:
list_of_dates_flats = results_selected['dayObs'].unique() 
list_of_dates_flats

array(['2021-02-16', '2021-02-17', '2021-02-18', '2021-03-11',
       '2021-06-08', '2021-06-09', '2021-07-07', '2021-07-08',
       '2021-09-07', '2021-09-08', '2021-09-09', '2021-10-05',
       '2021-10-06', '2021-10-07', '2021-11-02', '2021-11-04',
       '2022-02-15', '2022-02-16', '2022-02-17'], dtype=object)

In [18]:
Ndates=len(list_of_dates_flats)
Ndates

19

## Select of dates

In [19]:
idx=-1
night_sel = list_of_dates_flats[idx]
night_sel

'2022-02-17'

In [20]:
results_selected = results_selected[results_selected['dayObs'] == night_sel]

## List of filters

In [21]:
list_of_filters = results_selected['filter'].unique()
list_of_filters

array(['SDSSr~empty'], dtype=object)

## Loop on nights

- generate one file per night and per filter

In [22]:
for filt in list_of_filters:
    cut = results_selected['filter'] == filt
    df = results_selected[cut]
    df_sel = df[['dayObs', 'seqNum','filter','imageType']]
    df_sel = df_sel.sort_values(["seqNum"], ascending=True)
    print("---------------------",night_sel,' :: ',filt,"-----------------------------------------------")
    print(df_sel)

--------------------- 2022-02-17  ::  SDSSr~empty -----------------------------------------------
           dayObs  seqNum       filter imageType
11994  2022-02-17       4  SDSSr~empty      FLAT
12035  2022-02-17      45  SDSSr~empty      FLAT
12036  2022-02-17      46  SDSSr~empty      FLAT
12037  2022-02-17      47  SDSSr~empty      FLAT
12038  2022-02-17      48  SDSSr~empty      FLAT
12039  2022-02-17      49  SDSSr~empty      FLAT
12040  2022-02-17      50  SDSSr~empty      FLAT
12041  2022-02-17      51  SDSSr~empty      FLAT
12042  2022-02-17      52  SDSSr~empty      FLAT
12043  2022-02-17      53  SDSSr~empty      FLAT
12044  2022-02-17      54  SDSSr~empty      FLAT
12045  2022-02-17      55  SDSSr~empty      FLAT
12046  2022-02-17      56  SDSSr~empty      FLAT
12047  2022-02-17      57  SDSSr~empty      FLAT
12048  2022-02-17      58  SDSSr~empty      FLAT
12049  2022-02-17      59  SDSSr~empty      FLAT
12050  2022-02-17      60  SDSSr~empty      FLAT
12051  2022-02-17      61  SDSSr~empty      FLAT
12052  2022-02-17      62  SDSSr~empty      FLAT
12053  2022-02-17      63  SDSSr~empty      FLAT
12054  2022-02-17      64  SDSSr~empty      FLAT

In [23]:
for filt in list_of_filters:
    
    # prepare output
    filename_out = "visitflat_" + night_sel +"_"+ filt + ".list"
    
    cut = results_selected['filter'] == filt
    df = results_selected[cut]
    #df_sel = df[['dayObs', 'seqNum']]
    df_sel = df[['dayObs', 'seqNum','filter','imageType']]
    df_sel = df_sel.sort_values(["seqNum"], ascending=True)
    
    print("------------",filename_out,"----------------------------")
    print(df_sel)
    
    # build the line
    #df_sel['line'] = df_sel.apply(lambda row: "--id dayObs=\'" + row['dayObs'] +"\' seqNum="+ str(row['seqNum']),axis = 1)
    df_sel['line'] = df_sel.apply(lambda row: "--id dayObs=" + row['dayObs'] + " seqNum="+ str(row['seqNum']),axis = 1)
    
    
  
    # save file  
    df_out = df_sel[["line"]]
    df_out.to_csv(filename_out, index=False, header=None)

------------ visitflat_2022-02-17_SDSSr~empty.list ----------------------------
           dayObs  seqNum       filter imageType
11994  2022-02-17       4  SDSSr~empty      FLAT
12035  2022-02-17      45  SDSSr~empty      FLAT
12036  2022-02-17      46  SDSSr~empty      FLAT
12037  2022-02-17      47  SDSSr~empty      FLAT
12038  2022-02-17      48  SDSSr~empty      FLAT
12039  2022-02-17      49  SDSSr~empty      FLAT
12040  2022-02-17      50  SDSSr~empty      FLAT
12041  2022-02-17      51  SDSSr~empty      FLAT
12042  2022-02-17      52  SDSSr~empty      FLAT
12043  2022-02-17      53  SDSSr~empty      FLAT
12044  2022-02-17      54  SDSSr~empty      FLAT
12045  2022-02-17      55  SDSSr~empty      FLAT
12046  2022-02-17      56  SDSSr~empty      FLAT
12047  2022-02-17      57  SDSSr~empty      FLAT
12048  2022-02-17      58  SDSSr~empty      FLAT
12049  2022-02-17      59  SDSSr~empty      FLAT
12050  2022-02-17      60  SDSSr~empty      FLAT
12051  2022-02-17      61  SDSSr~empty      FLAT
12052  2022-02-17      62  SDSSr~empty      FLAT
12053  2022-02-17      63  SDSSr~empty      FLAT
12054  2022-02-17      64  SDSSr~empty      FLAT