# Build filelist from registry.sqlite for dispersers


- author : Sylvie Dagoret-Campagne
- affiliation : IJCLab/IN2P3/CNRS
- creation date : January 18th 2022
- update : February 24th 2022


- purpose create ascii files with exposure identifier in order to call DM-Stack pipeline

In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import pandas as pd

import sqlite3

In [2]:
def read_sqlite(dbfile):
    import sqlite3
    from pandas import read_sql_query, read_sql_table

    with sqlite3.connect(dbfile) as dbcon:
        tables = list(read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", dbcon)['name'])
        out = {tbl : read_sql_query(f"SELECT * from {tbl}", dbcon) for tbl in tables}

    return out

## Configuration

In [3]:
# database file
database_file = "registry.sqlite3"

## Read DB

### Guess of list of tables in a Dictionnary

In [4]:
dict_db = read_sqlite(database_file)

In [5]:
dict_db.keys()

dict_keys(['raw', 'sqlite_sequence', 'raw_visit'])

### Put selected table in a pandas dataframe

In [6]:
dat = sqlite3.connect(database_file)

In [7]:
query = dat.execute("SELECT * From raw")

In [8]:
cols = [column[0] for column in query.description]

In [9]:
results= pd.DataFrame.from_records(data = query.fetchall(), columns = cols)

In [10]:
results

,id,dayObs,seqNum,visit,detector,detectorName,filter,dateObs,date,expTime,object,imageType,wavelength,expGroup,obsid,expId
0,1,2021-06-08,1,2031133798900000,0,S00,RG610~holo4_003,2021-06-08T20:23:00.082,2021-06-08T20:23:00.082,0.0,azel_target,BIAS,-666,2021-06-08T20:22:59.890,AT_O_20210608_000001,2021060800001
1,2,2021-06-08,2,2031134348450000,0,S00,RG610~holo4_003,2021-06-08T20:23:55.021,2021-06-08T20:23:55.021,0.0,azel_target,BIAS,-666,2021-06-08T20:23:54.845,AT_O_20210608_000002,2021060800002
2,3,2021-06-08,3,2031134393460000,0,S00,RG610~holo4_003,2021-06-08T20:23:59.516,2021-06-08T20:23:59.516,0.0,azel_target,BIAS,-666,2021-06-08T20:23:59.346,AT_O_20210608_000003,2021060800003
3,4,2021-06-08,4,2031134438450000,0,S00,RG610~holo4_003,2021-06-08T20:24:04.019,2021-06-08T20:24:04.019,0.0,azel_target,BIAS,-666,2021-06-08T20:24:03.845,AT_O_20210608_000004,2021060800004
4,5,2021-06-08,5,2031134483610000,0,S00,RG610~holo4_003,2021-06-08T20:24:08.527,2021-06-08T20:24:08.527,0.0,azel_target,BIAS,-666,2021-06-08T20:24:08.361,AT_O_20210608_000005,2021060800005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,12756,2022-02-17,765,2251058140450000,0,S00,SDSSg~empty,2022-02-18T09:25:53.560,2022-02-18T09:25:53.560,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:23:34.045,AT_O_20220217_000765,2022021700765
12756,12757,2022-02-17,766,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:26:52.861,2022-02-18T09:26:52.861,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000766,2022021700766
12757,12758,2022-02-17,767,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:27:25.852,2022-02-18T09:27:25.852,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000767,2022021700767
12758,12759,2022-02-17,768,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:22.143,2022-02-18T09:28:22.143,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000768,2022021700768
12759,12760,2022-02-17,769,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:55.127,2022-02-18T09:28:55.127,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000769,2022021700769

## sort according day and time

In [11]:
results_sorted = results.sort_values(["dayObs", "seqNum"], ascending=True)

In [12]:
results_sorted

,id,dayObs,seqNum,visit,detector,detectorName,filter,dateObs,date,expTime,object,imageType,wavelength,expGroup,obsid,expId
8687,8688,2021-02-16,1,1934346219930000,0,S00,empty~empty,2021-02-16T19:50:22.184,2021-02-16T19:50:22.184,0.0,azel_target,BIAS,-666,2021-02-16T19:50:21.993,AT_O_20210216_000001,2021021600001
8688,8689,2021-02-16,2,1934362834080000,0,S00,empty~empty,2021-02-16T20:18:03.588,2021-02-16T20:18:03.588,0.0,azel_target,BIAS,-666,2021-02-16T20:18:03.408,AT_O_20210216_000002,2021021600002
8689,8690,2021-02-16,3,1934362963860000,0,S00,empty~empty,2021-02-16T20:18:16.563,2021-02-16T20:18:16.563,0.0,azel_target,BIAS,-666,2021-02-16T20:18:16.386,AT_O_20210216_000003,2021021600003
8690,8691,2021-02-16,4,1934363094110000,0,S00,empty~empty,2021-02-16T20:18:29.581,2021-02-16T20:18:29.581,0.0,azel_target,BIAS,-666,2021-02-16T20:18:29.411,AT_O_20210216_000004,2021021600004
8691,8692,2021-02-16,5,1934363223760000,0,S00,empty~empty,2021-02-16T20:18:42.546,2021-02-16T20:18:42.546,0.0,azel_target,BIAS,-666,2021-02-16T20:18:42.376,AT_O_20210216_000005,2021021600005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,12756,2022-02-17,765,2251058140450000,0,S00,SDSSg~empty,2022-02-18T09:25:53.560,2022-02-18T09:25:53.560,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:23:34.045,AT_O_20220217_000765,2022021700765
12756,12757,2022-02-17,766,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:26:52.861,2022-02-18T09:26:52.861,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000766,2022021700766
12757,12758,2022-02-17,767,2251059032260000,0,S00,SDSSi~empty,2022-02-18T09:27:25.852,2022-02-18T09:27:25.852,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:25:03.226,AT_O_20220217_000767,2022021700767
12758,12759,2022-02-17,768,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:22.143,2022-02-18T09:28:22.143,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000768,2022021700768
12759,12760,2022-02-17,769,2251059905630000,0,S00,SDSSr~empty,2022-02-18T09:28:55.127,2022-02-18T09:28:55.127,30.0,LATISS_E6A_00000034,SKYEXP,-666,2022-02-18T09:26:30.563,AT_O_20220217_000769,2022021700769

## Nights

In [13]:
list_of_nights = results_sorted['dayObs'].unique()
list_of_nights

array(['2021-02-16', '2021-02-17', '2021-02-18', '2021-03-11',
       '2021-06-08', '2021-06-09', '2021-06-10', '2021-07-06',
       '2021-07-07', '2021-07-08', '2021-09-07', '2021-09-08',
       '2021-09-09', '2021-10-05', '2021-10-06', '2021-10-07',
       '2021-11-02', '2021-11-03', '2021-11-04', '2022-02-15',
       '2022-02-16', '2022-02-17'], dtype=object)

## Filters

In [14]:
list_of_filters = results_sorted['filter'].unique()
list_of_filters

array(['empty~empty', 'RG610~empty', 'RG610~holo4_003', 'empty~holo4_003',
       'empty~ronchi90lpmm', 'RG610~ronchi90lpmm',
       'quadnotch1~ronchi90lpmm', 'BG40~empty', 'BG40~ronchi90lpmm',
       'RG610~ronchi170lpmm', 'BG40~holo4_003', 'unknown~unknown',
       'FELH0600~holo4_003', 'FELH0600~empty', 'FELH0600~ronchi170lpmm',
       'empty~ronchi170lpmm', 'quadnotch1~ronchi170lpmm',
       'BG40~ronchi170lpmm', 'quadnotch1~holo4_003',
       'FELH0600~ronchi90lpmm', 'SDSSg~empty', 'SDSSg~ronchi170lpmm',
       'SDSSg~holo4_003', 'quadnotch1~empty', 'SDSSr~empty',
       'SDSSi~empty', 'SDSSr~holo4_003'], dtype=object)

In [15]:
selected_filters = []
for filt in list_of_filters:
    flag_sel = (filt.find('holo4') != -1) or (filt.find('ronchi90lpmm') != -1) or (filt.find('ronchi170lpmm') != -1)
    if flag_sel:
        selected_filters.append(filt) 
selected_filters = np.array(selected_filters)
selected_filters

array(['RG610~holo4_003', 'empty~holo4_003', 'empty~ronchi90lpmm',
       'RG610~ronchi90lpmm', 'quadnotch1~ronchi90lpmm',
       'BG40~ronchi90lpmm', 'RG610~ronchi170lpmm', 'BG40~holo4_003',
       'FELH0600~holo4_003', 'FELH0600~ronchi170lpmm',
       'empty~ronchi170lpmm', 'quadnotch1~ronchi170lpmm',
       'BG40~ronchi170lpmm', 'quadnotch1~holo4_003',
       'FELH0600~ronchi90lpmm', 'SDSSg~ronchi170lpmm', 'SDSSg~holo4_003',
       'SDSSr~holo4_003'], dtype='<U24')

## Selection of rows

In [16]:
def isdisperser(row):
    #print(row["filter"])
    if str(row["filter"]) in selected_filters:
        return True
    
    else:
        return False

In [17]:
results_sorted["selected"] = results_sorted.apply(isdisperser,axis=1)

In [18]:
results_selected = results_sorted[results_sorted.selected]

## Loop on nights

- generate one file per night

In [19]:
for night_sel in list_of_nights:
    cut = results_selected['dayObs'] == night_sel 
    df = results_selected[cut]
    df_sel = df[['dayObs', 'seqNum']]
    
    
    # build the line
    df_sel['line'] = df_sel.apply(lambda row: "--id dayObs=\'" + row['dayObs'] +"\' seqNum="+ str(row['seqNum']),axis = 1)
    
    
    # prepare output
    filename_out = "visitdispersers_"+ night_sel+".list"
    
    df_out = df_sel[["line"]]
    df_out.to_csv(filename_out, index=False, header=None)

/tmp/ipykernel_3321/1398922832.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sel['line'] = df_sel.apply(lambda row: "--id dayObs=\'" + row['dayObs'] +"\' seqNum="+ str(row['seqNum']),axis = 1)